name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: What feature would you like to see added?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation & Use Case
      description: Why do you need this feature? What problem does it solve?
      placeholder: |
        - What problem are you trying to solve?
        - How would this feature help you?
        - What's your current workaround (if any)?
    validations:
      required: true

  - type: textarea
    id: detailed-description
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the feature
      placeholder: |
        - How should this feature work?
        - What should the user interface look like?
        - Any specific requirements or constraints?

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        # Example command usage:
        mcp-forge new-feature --option value
        
        # Example output:
        Feature working as expected...
      render: shell

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - CLI Interface
        - Template System
        - Configuration Management
        - Backup & Restore
        - Profile Management
        - Bulk Operations
        - Validation & Health
        - Import/Export
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my usage
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: |
        - Other tools that provide this functionality
        - Different approaches to solving the problem
        - Workarounds you've tried

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas on how this could be implemented?
      placeholder: |
        - Technical approach suggestions
        - API design ideas
        - Integration points with existing features

  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility Considerations
      description: Please check all that apply
      options:
        - label: This feature should work on all platforms (Windows, macOS, Linux)
        - label: This feature should maintain backward compatibility
        - label: This feature should follow existing CLI patterns
        - label: This feature should integrate with existing templates

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I have provided sufficient detail for evaluation
          required: true 